from typing import Protocol, Any
from domain.bettor import Bettor

class BettorRepository(Protocol):
	def add(self, bettor: Bettor) -> None:
		...

	def get(self, bettor_id: int) -> Bettor:
		...

	def liste(self) -> list[Bettor]:
		...

	def exists_by_name(self, name: str) -> bool:
		...
	def list_bets(self, bettor_id: int) -> list[int]:
		...	
	def get_bank(self) -> float:
		...
	def export_state(self) -> dict:
		...
	def import_state(self, state: dict) -> None:
		...