from typing import Protocol, Any
from domain.match import Match

class MatchRepository(Protocol):
	def add(self, match: Match) -> None:
		...

	def get(self, match_id: int) -> Match:
		...

	def liste(self) -> list[Match]:
		...

	def exists(self, match_id: int) -> bool:
		...
	def export_state(self) -> dict:
		...
	def import_state(self, state: dict) -> None:
		...
